=== Matthew-Jeffries/EDS/src/eds-messaging-core/src/main/resources/QueueReaderConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:include schemaLocation="Pipeline.xsd"/>
    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:pattern value=".*[^\s].*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="QueueReaderConfiguration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Credentials">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Username" type="nonEmptyString" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="Password" type="nonEmptyString" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Nodes" type="nonEmptyString" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Exchange" type="nonEmptyString" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Queue" type="nonEmptyString" minOccurs="0" maxOccurs="1"/>
                <xs:element name="RoutingKeys" type="nonEmptyString" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Pipeline" type="Pipeline" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Matthew-Jeffries/EDS/src/eds-queuereader/src/main/resources/Subscriber.xml
<?xml version="1.0" encoding="UTF-8"?>
<QueueReaderConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../eds-messaging-core/src/main/resources/QueueReaderConfiguration.xsd">
    <Credentials>
        <Username>username</Username>
        <Password>password</Password>
    </Credentials>
    <Nodes>192.168.0.1:1000, 192.168.0.2:2000</Nodes>
    <Queue>Subscriber-Orgs1000-2000</Queue>
    <Pipeline>
        <PostToSubscriberWebService/>
    </Pipeline>
</QueueReaderConfiguration>

=== Matthew-Jeffries/EDS/src/eds-queuereader/src/main/resources/Inbound.xml
<?xml version="1.0" encoding="UTF-8"?>
<QueueReaderConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="QueueReaderConfiguration.xsd">
    <Credentials>
        <Username>username</Username>
        <Password>password</Password>
    </Credentials>
    <Nodes>192.168.0.1:1000, 192.168.0.2:2000</Nodes>
    <Exchange>Inbound</Exchange>
    <Queue>Inbound-Orgs1000-2000</Queue>
    <RoutingKeys>Org1,Org2,Org3</RoutingKeys>
    <MessagePipelineClass>org.endeavourhealth.queuereader.pipeline.InboundPipeline</MessagePipelineClass>
</QueueReaderConfiguration>

=== Matthew-Jeffries/EDS/src/eds-queuereader/src/main/resources/Response.xml
<?xml version="1.0" encoding="UTF-8"?>
<QueueReaderConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="QueueReaderConfiguration.xsd">
    <Credentials>
        <Username>username</Username>
        <Password>password</Password>
    </Credentials>
    <Nodes>192.168.0.1:1000, 192.168.0.2:2000</Nodes>
    <Exchange>Response</Exchange>
    <Queue>Response-Orgs1000-2000</Queue>
    <RoutingKeys>Org1,Org2,Org3</RoutingKeys>
    <MessagePipelineClass>org.endeavourhealth.queuereader.pipeline.ResponsePipeline</MessagePipelineClass>
</QueueReaderConfiguration>
