=== Matthew-Jeffries/EDS/src/eds-messaging-core/src/main/resources/SftpReaderConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="Common.xsd"/>

    <xs:element name="SftpReaderConfiguration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="InstanceId" type="nonEmptyString" minOccurs="1" maxOccurs="1"/>
                <xs:element name="DatabaseConnections" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SftpReader" type="DatabaseConnection" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="Logback" type="DatabaseConnection" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="DatabaseConnection">
        <xs:sequence>
            <xs:element name="Hostname" type="nonEmptyString" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Port" type="xs:integer" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Database" type="nonEmptyString" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Username" type="nonEmptyString" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Password" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Matthew-Jeffries/EDS/src/eds-sftpreader/src/main/resources/SftpReaderConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<SftpReaderConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:noNamespaceSchemaLocation="../../../../eds-messaging-core/src/main/resources/SftpReaderConfiguration.xsd">

    <InstanceId>EMIS001</InstanceId>
    <PostgresConnetion>
        <Hostname>localhost</Hostname>
        <Port>5432</Port>
        <Database>sftpreader</Database>
        <Username>postgres</Username>
        <Password></Password>
    </PostgresConnetion>

</SftpReaderConfiguration>
