=== Matthew-Jeffries/EDS/src/eds-messaging/eds-messaging/src/main/resources/RouteConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="RouteConfiguration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Service" type="Service"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Service">
		<xs:sequence>
			<xs:element name="Id" type="xs:string"/>
			<xs:element name="ReceivePorts">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="ReceivePort" type="ReceivePort"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="MessageTypes">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="MessageType" type="MessageType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="SendPorts">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="SendPort" type="SendPortType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Routes">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Route" type="Route"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ReceivePort">
		<xs:sequence>
			<xs:element name="Id" type="xs:string"/>
			<xs:choice>
				<xs:element name="Http">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Port" type="xs:int"/>
							<xs:element name="Path" type="xs:string"/>
							<xs:element name="Methods" type="xs:string"/>
							<xs:element name="IncludeSubPaths" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Sftp">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Path" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="RabbitMQ">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="QueueName" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:element name="ReceivePortHandlerClass" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SendPortType">
		<xs:sequence>
			<xs:element name="Id" type="xs:string"/>
			<xs:choice>
				<xs:element name="Http" type="xs:string"/>
				<xs:element name="RabbitMQ" type="xs:string"/>
			</xs:choice>
			<xs:element name="SendPortClass" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MessageType">
		<xs:sequence>
			<xs:element name="Id" type="xs:string"/>
			<xs:element name="LogInbound" type="xs:boolean"/>
			<xs:element name="LogOutbound" type="xs:boolean"/>
			<xs:element name="MessageProcessorClass" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Route">
		<xs:sequence>
			<xs:element name="Id"/>
			<xs:element name="SendPortId"/>
			<xs:element name="ReceivePortId"/>
			<xs:element name="MessageTypes">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="Id"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Matthew-Jeffries/EDS/src/eds-messaging/eds-messaging-plugin-dataservice/src/main/resources/RouteConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<RouteConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///../../../../eds-messaging/src/main/resources/RouteConfiguration.xsd">
	<Service>
		<Id>fhir-messaging</Id>

		<ReceivePorts>
			<ReceivePort>
				<Id>endeavour-envelope-receiver</Id>
				<Http>
					<Port>8080</Port>
					<Path>/dataservice/$post-endeavour-envelope</Path>
					<Methods>post</Methods>
					<IncludeSubPaths>false</IncludeSubPaths>
				</Http>
				<ReceivePortHandlerClass>org.endeavourhealth.messaging.plugin.dataservice.EndeavourEnvelopeReceivePort</ReceivePortHandlerClass>
			</ReceivePort>
		</ReceivePorts>
		<MessageTypes>
			<MessageType>
				<Id>PostEOpenPatientRecord1-0</Id>
				<LogInbound>true</LogInbound>
				<LogOutbound>true</LogOutbound>
				<MessageProcessorClass>org.endeavourhealth.messaging.plugin.dataservice.PostEOpenPatientRecordProcessor</MessageProcessorClass>
			</MessageType>
		</MessageTypes>
		<SendPorts>
			<SendPort>
				<Id>fhir-messaging-rabbitmq</Id>
				<RabbitMQ>

				</RabbitMQ>
				<SendPortClass/>
			</SendPort>
		</SendPorts>
		<Routes>
			<Route>
				<Id/>
				<SendPortId>fhir-messaging-http</SendPortId>
				<ReceivePortId>fhir-messaging-rabbitmq</ReceivePortId>
				<MessageTypes>
					<Id>UploadEmisOpenPatient-v0-0-2</Id>
				</MessageTypes>
			</Route>
		</Routes>
	</Service>
</RouteConfiguration>
