=== Matthew-Jeffries/EDS/src/eds-utilities/src/main/resources/LocalConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="LocalConfiguration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="InstanceName" type="NonEmptyString" minOccurs="1" maxOccurs="1"/>
                <xs:element name="DatabaseConnections" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DatabaseConnection" type="DatabaseConnection" minOccurs="1" maxOccurs="2"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="DatabaseConnection">
        <xs:sequence>
            <xs:element name="DatabaseType" type="NonEmptyString" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Hostname" type="NonEmptyString" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Port" type="xs:integer" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Database" type="NonEmptyString" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Username" type="NonEmptyString" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Password" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="DatabaseType" final="restriction" >
        <xs:restriction base="xs:string">
            <xs:enumeration value="sftpreader"/>
            <xs:enumeration value="hl7receiver"/>
            <xs:enumeration value="logback"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="NonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:pattern value=".*[^\s].*"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Matthew-Jeffries/EDS/src/eds-utilities/src/main/resources/LocalConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<LocalConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:noNamespaceSchemaLocation="LocalConfiguration.xsd">

    <InstanceName>TEST001</InstanceName>

    <DatabaseConnections>
        <DatabaseConnection>
            <DatabaseType>sftpreader</DatabaseType>
            <Hostname>localhost</Hostname>
            <Port>5432</Port>
            <Database>sftpreader</Database>
            <Username>postgres</Username>
            <Password></Password>
        </DatabaseConnection>
        <DatabaseConnection>
            <DatabaseType>hl7receiver</DatabaseType>
            <Hostname>localhost</Hostname>
            <Port>5432</Port>
            <Database>hl7receiver</Database>
            <Username>postgres</Username>
            <Password></Password>
        </DatabaseConnection>
    </DatabaseConnections>

</LocalConfiguration>
