=== Matthew-Jeffries/EDS/src/eds-messaging/eds-messaging/src/main/java/org/endeavourhealth/core/messaging/configuration/schema/serviceConfiguration/ServiceConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 rel. 2 sp1 (x64) (http://www.altova.com) by Jonny Rylands (Egton Medical Information System) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="nonEmptyString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:pattern value=".*[^\s].*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="ServiceConfiguration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Service" type="Service"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Service">
		<xs:sequence>
			<xs:element name="Id" type="nonEmptyString"/>
			<xs:element name="Listeners">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="HttpListener" type="HttpListener" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element name="RabbitListener" type="RabbitListener" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element name="SftpListener" type="SftpListener" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="MessageTypes">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="MessageType" type="MessageType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MessageType">
		<xs:sequence>
			<xs:element name="Id" type="xs:string"/>
			<xs:element name="LogInbound" type="xs:boolean"/>
			<xs:element name="LogOutbound" type="xs:boolean"/>
			<xs:element name="MessageProcessorClass" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HttpListener">
		<xs:sequence>
			<xs:element name="Port" type="xs:int"/>
			<xs:element name="Receiver" type="HttpReceiver" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RabbitListener">
		<xs:sequence>
			<xs:element name="Credentials">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Username" type="nonEmptyString"/>
						<xs:element name="Password" type="nonEmptyString"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Nodes" type="nonEmptyString" minOccurs="0"/>
			<xs:element name="Receiver" type="RabbitReceiver" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
    <xs:complexType name="SftpListener">
        <xs:sequence>
            <xs:element name="Host" type="nonEmptyString"/>
            <xs:element name="Port" type="xs:int"/>
            <xs:element name="Credentials">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Username" type="nonEmptyString"/>
                        <xs:element name="Password" type="nonEmptyString"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Receiver" type="SftpReceiver" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
	<xs:complexType name="HttpReceiver">
		<xs:sequence>
			<xs:element name="Path" type="nonEmptyString"/>
			<xs:element name="Methods" type="nonEmptyString" minOccurs="0"/>
			<xs:element name="IncludeSubPaths" type="xs:boolean" default="false" minOccurs="0"/>
			<xs:element name="ReceiverClass" type="nonEmptyString"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RabbitReceiver">
		<xs:sequence>
			<xs:element name="Queue" type="nonEmptyString"/>
			<xs:element name="Exchange" type="nonEmptyString" minOccurs="0"/>
			<xs:element name="RoutingKey" type="nonEmptyString" minOccurs="0"/>
			<xs:element name="ReceiverClass" type="nonEmptyString"/>
		</xs:sequence>
	</xs:complexType>
    <xs:complexType name="SftpReceiver">
        <xs:sequence>
            <xs:element name="Path" type="nonEmptyString"/>
            <xs:element name="Filename" type="nonEmptyString" minOccurs="0"/>
            <xs:element name="PollTime" type="xs:int"/>
            <xs:element name="ReceiverClass" type="nonEmptyString"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Matthew-Jeffries/EDS/src/eds-messaging/eds-messaging-plugin-dataservice/src/main/resources/ServiceConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<ServiceConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///../../../../eds-messaging/src/main/java/org/endeavourhealth/messaging/configuration/schema/serviceConfiguration/ServiceConfiguration.xsd">
	<Service>
		<Id>endeavour-dataservice</Id>
		<Listeners>
			<HttpListener>
				<Port>8080</Port>
				<Receiver>
					<Path>/dataservice/$post-endeavour-envelope</Path>
					<Methods>post</Methods>
					<ReceiverClass>org.endeavourhealth.messaging.plugin.dataservice.EndeavourEnvelopeReceiver</ReceiverClass>
				</Receiver>
				<Receiver>
					<Path>/dataservice/rest/</Path>
					<IncludeSubPaths>true</IncludeSubPaths>
					<ReceiverClass>org.endeavourhealth.messaging.plugin.dataservice.EndeavourEnvelopeReceiver</ReceiverClass>
				</Receiver>
			</HttpListener>
			<!--<RabbitListener>-->
				<!--<Credentials>-->
					<!--<Username>username</Username>-->
					<!--<Password>password</Password>-->
				<!--</Credentials>-->
				<!--<Nodes>192.168.0.1, 192.168.0.2:10001, 192.168.0.3:12345</Nodes>-->
				<!--<Receiver>-->
					<!--<Queue>MyQueue</Queue>-->
					<!--<Exchange>MyExchange</Exchange>-->
					<!--<RoutingKey>MyKey</RoutingKey>-->
					<!--<ReceiverClass>org.endeavourhealth.messaging.plugin.dataservice.EndeavourEnvelopeReceiver</ReceiverClass>-->
				<!--</Receiver>-->
			<!--</RabbitListener>-->
            <SftpListener>
                <Host>127.0.0.1</Host>
                <Port>80</Port>
                <Credentials>
                    <Username>username</Username>
                    <Password>password</Password>
                </Credentials>
                <Receiver>
                    <Path>./</Path>
                    <Filename>*.dat</Filename>
                    <PollTime>30</PollTime>
                    <ReceiverClass>org.endeavourhealth.messaging.plugin.dataservice.EndeavourEnvelopeReceiver</ReceiverClass>
                </Receiver>
            </SftpListener>
		</Listeners>

		<MessageTypes>
			<MessageType>
				<Id>PostEOpenPatientRecord1-0</Id>
				<LogInbound>true</LogInbound>
				<LogOutbound>true</LogOutbound>
				<MessageProcessorClass>org.endeavourhealth.messaging.plugin.dataservice.PostEOpenPatientRecordProcessor</MessageProcessorClass>
			</MessageType>
		</MessageTypes>

	</Service>
</ServiceConfiguration>
